Implement REST API
innovember/devops-training pull request #3
Opened 2021-06-24 17:59 UTC by innovember

2021-06-25 14:27 UTC, renehernandez requested changes

2021-06-25 14:27 UTC, renehernandez commented on internal/message/delivery/msg_delivery.go
> +	mux.HandleFunc(messageRoute, mh.CreateMessage).Methods("POST")
The route to create a new message shouldn't require an existing id. It should be possible to create a message by invoking `localhost:8081/api/v1/messages` using a POST request and the JSON payload

2021-06-25 14:27 UTC, renehernandez commented on internal/models/message.go
> +	ID        int       `json:"id"`
This should support `omitempty`. That way is not necessary to pass the `id` as value during a new message creation

2021-06-25 14:27 UTC, renehernandez commented on internal/models/message.go
> +	EditedAt  time.Time `json:"editedAt"`
This should support `omitempty`. That way is not necessary to pass the `EditedAt ` as value during a new message creation

2021-06-25 14:27 UTC, renehernandez commented on internal/models/message.go
> +	CreatedAt time.Time `json:"createdAt"`
This should support `omitempty`. That way is not necessary to pass the `createdAt` as value during a new message creation

2021-06-25 14:27 UTC, renehernandez commented on internal/message/delivery/msg_delivery.go
> +func (mh *MessageHandler) CreateMessage(w http.ResponseWriter, r *http.Request) {
The `CreateMessage` method should handle setting the `createdAt` field before saving to the database

2021-06-25 14:27 UTC, renehernandez commented on internal/message/delivery/msg_delivery.go
> +func (mh *MessageHandler) UpdateMessage(w http.ResponseWriter, r *http.Request) {
The `UpdateMessage` method should handle setting the `editAt` field before saving to the database

2021-06-25 14:29 UTC, renehernandez commented
To better follow conventions, could you rename the `MessageUsecase` files and objects to `MessagesController`? That makes it easier for people onboarding to a project to understand the separation of responsibilities between controllers and models in an API design

2021-06-25 14:30 UTC, renehernandez commented
The `api` folder should be at the root level, not under the `cmd` folder. The `cmd` will only host the future cli implementation

2021-06-25 16:05 UTC, innovember commented on internal/models/message.go
> +	ID        int       `json:"id"`
Done

2021-06-25 16:05 UTC, innovember commented on internal/models/message.go
> +	EditedAt  time.Time `json:"editedAt"`
Done

2021-06-25 16:05 UTC, innovember commented on internal/models/message.go
> +	CreatedAt time.Time `json:"createdAt"`
Done

2021-06-25 16:07 UTC, innovember commented on internal/message/delivery/msg_delivery.go
> +func (mh *MessageHandler) CreateMessage(w http.ResponseWriter, r *http.Request) {
There is default insertion to table where I initialized table (you could see it in ./scripts/init.sql, Default method adds value, if you dont mention filed in query)

2021-06-25 16:09 UTC, innovember commented on internal/message/delivery/msg_delivery.go
> +func (mh *MessageHandler) UpdateMessage(w http.ResponseWriter, r *http.Request) {
In ./internal/message/repository/message_pg_repository.go file in Update method , there is time.Now() value for edit time 
I added it there, rather than initializing it in handler

2021-06-25 16:09 UTC, innovember commented
> To better follow conventions, could you rename the `MessageUsecase` files and objects to `MessagesController`? That makes it easier for people onboarding to a project to understand the separation of responsibilities between controllers and models in an API design

Done

2021-06-25 16:09 UTC, innovember commented
> The `api` folder should be at the root level, not under the `cmd` folder. The `cmd` will only host the future cli implementation

Done

2021-06-29 13:24 UTC, renehernandez commented
@innovember Moving forward, can we limit the number of changes that we are introducing as part of the same PR. Smaller changes make it easy for me (and others, in general) to review the code

2021-06-29 13:28 UTC, renehernandez commented
What is the purpose of the `Dockerfile` vs `api.Dockerfile`? 

Within `Dockerfile`, It isn't good practice to bundle different processes within a single docker image. postgres should be on its own container/image

2021-06-29 13:29 UTC, innovember commented
> @innovember Moving forward, can we limit the number of changes that we are introducing as part of the same PR. Smaller changes make it easy for me (and others, in general) to review the code

yeah, ok
lets close this one

2021-06-29 13:37 UTC, innovember commented
> What is the purpose of the `Dockerfile` vs `api.Dockerfile`?
> 
> Within `Dockerfile`, It isn't good practice to bundle different processes within a single docker image. postgres should be on its own container/image

yeah, I know about that ,at first I tried to create my own image at docker hub, then use it as reference in compose, its just test version ( about Dockerfile,its a test version)
Then , I implemented compose with different services , it will be the one to deploy rest api. There api.Dockerfile for restapi service, it implements downloading of modules, and build of api , and running of api, may be instead of using dockerfile,I could wrote all of it in  commands in api service, but I thought it will be better to split it to another file

2021-07-01 14:17 UTC, renehernandez commented
> > @innovember Moving forward, can we limit the number of changes that we are introducing as part of the same PR. Smaller changes make it easy for me (and others, in general) to review the code
> 
> yeah, ok
> lets close this one

Yup, let's start over and implement the changes in smaller chunks

2021-07-01 14:23 UTC, renehernandez commented
Instead of implementing all the low level HTTP server using the standard Golang library, I suggest to use a higher level web framework, such as https://gofiber.io. The focus here is not to write a web server, but use an API to drive the different uses cases that we want to explore

2021-07-02 12:52 UTC, closed without merging